### PR TITLE
Working swipe to delete.

### PR DESCRIPTION
**Pull request by arjunkalburgi**

### CODE REVIEW

**Comment by OpenSnack** [comment]
If we're swiping to delete, we should have a Snackbar undo option since a Request is in itself pretty important and would suck to accidentally swipe away.

**Comment by OpenSnack** [comment]
The best way to do Snackbar undo would probably be to have the app not delete the request until the Snackbar goes away (and we didn't press undo.)

**Comment by arjunkalburgi** [comment]
@snackthyme That would work, I can adjust that - but @gantonious mentioned there may be problems with this code since we have a new adapter. So....

**Comment by gantonious** [comment]
We should be able to sort it out. I just want to deal with it after the adapter changes are merged in.

**Comment by arjunkalburgi** [comment]
Only thing that hasn't been tested in this is that it doesn't remove non-PendingRequest items. It should because of the if statement RiderSummaryFragment:270 but it hasn't been tested.

**Pull request merged**
